[package]
name = "threshold_crypto"
version = "0.1.0"
authors = ["Andreas Fackler <AndreasFackler@gmx.de>",
           "Peter van Nostrand <jnz@riseup.net>"]
description = "Pairing threshold cryptography"
license = "LGPL-3.0"
repository = "https://github.com/poanetwork/threshold_crypto"
readme = "https://github.com/poanetwork/threshold_crypto/blob/master/README.md"
keywords = ["pairing", "threshold"]
categories = ["cryptography"]

[dependencies]
byteorder = "1.2.3"
error-chain = "0.12.0"
init_with = "1.1.0"
log = "0.4.1"
pairing = { version = "0.14.2", features = ["u128-support"] }
protobuf = { version = "2.0.0", optional = true }
rand = "0.4.2"
rand_derive = "0.3.1"
ring = "^0.12"
serde = "1.0.55"
serde_derive = "1.0.55"

[features]
serialization-protobuf = [ "protobuf", "protobuf-codegen-pure" ]

[build-dependencies]
protobuf-codegen-pure = { version = "2.0.0", optional = true }

[dev-dependencies]
bincode = "1.0.0"
